/* ==========================================================
   IMPORTS & APP CONFIGURATION
========================================================== */
const express = require("express");
const cors = require("cors");
const path = require("path");
const PdfPrinter = require("pdfmake");
const { loadExcelData } = require("./dataLoader");

const app = express();
app.use(cors());
app.use(express.json());

/* ==========================================================
   LOAD EXCEL INTO MEMORY
========================================================== */
let excelData = loadExcelData();

/* ==========================================================
   FILTER UTILITY
========================================================== */
function applyFilters(data, query) {
  const keys = ["PF_NO", "BILL_UNIT", "DESIG", "STATION", "BOOTH"];
  let filtered = [...data];

  keys.forEach(key => {
    if (query[key]) {
      const q = String(query[key]).toLowerCase();
      filtered = filtered.filter(row =>
        String(row[key] || "").toLowerCase().includes(q)
      );
    }
  });

  return filtered;
}

/* ==========================================================
   PDF FONTS (Render-safe)
========================================================== */
const fonts = {
  Roboto: {
    normal: path.join(__dirname, "fonts/Roboto-Regular.ttf"),
    bold: path.join(__dirname, "fonts/Roboto-Bold.ttf"),
    italics: path.join(__dirname, "fonts/Roboto-Italic.ttf"),
    bolditalics: path.join(__dirname, "fonts/Roboto-BoldItalic.ttf")
  }
};

const printer = new PdfPrinter(fonts);

/* ==========================================================
   API: FETCH FILTERED DATA
========================================================== */
app.get("/api/data", (req, res) => {
  try {
    const { page = 1, limit = 10 } = req.query;

    const filtered = applyFilters(excelData, req.query);
    const total = filtered.length;

    const p = Math.max(1, parseInt(page));
    const l = Math.max(1, parseInt(limit));

    const start = (p - 1) * l;
    const sliced = filtered.slice(start, start + l);

    const processed = sliced.map((row, idx) => ({
      SR_No: start + idx + 1,
      ...row
    }));

    res.json({
      total,
      page: p,
      limit: l,
      data: processed
    });
  } catch (err) {
    console.error("Data API error:", err);
    res.status(500).json({ error: "Server error" });
  }
});

/* ==========================================================
   API: EXPORT PDF (WITH HEADER + FOOTER + LOGO)
========================================================== */
app.get("/api/export/pdf", (req, res) => {
  try {
    const filtered = applyFilters(excelData, req.query);

    const rows = filtered.map((r, i) => ({
      SR_No: i + 1,
      PF_NO: r.PF_NO,
      NAME: r.NAME,
      FATHER_NAME: r.FATHER_NAME,
      BILL_UNIT: r.BILL_UNIT,
      DESIG: r.DESIG,
      MOBILE_NO: r.MOBILE_NO,
      STATION: r.STATION,
      BOOTH: r.BOOTH
    }));

    const columns = [
      "SR_No",
      "PF_NO",
      "NAME",
      "FATHER_NAME",
      "BILL_UNIT",
      "DESIG",
      "MOBILE_NO",
      "STATION",
      "BOOTH"
    ];

    const widths = [35, 70, 110, 110, 60, 80, 90, 70, 70];

    const tableHeaders = columns.map(col => ({
      text: col,
      style: "tableHeader"
    }));

    const tableRows = rows.map(r =>
      columns.map(col => ({
        text: String(r[col] || ""),
        style: "tableCell"
      }))
    );

    /* --------------------- LOGO PATH ---------------------- */
    const logoPath = path.join(__dirname, "assets/logo.png");

    /* ------------------ PDF DOCUMENT STRUCTURE ------------------ */
    const docDefinition = {
      pageOrientation: "landscape",
      pageMargins: [40, 90, 40, 60], // room for header + footer

      /* -------- WATERMARK -------- */
      watermark: {
        text: "WCRMS KOTA",
        color: "#000000",
        opacity: 0.22,
        bold: true,
        angle: -45
      },

      /* -------- PAGE HEADER -------- */
      header: {
        margin: [40, 20, 40, 0],
        columns: [
          {
            image: logoPath,
            width: 60
          },
          {
            text: "WCRMS KOTA — Employee Filtered Report",
            alignment: "center",
            fontSize: 18,
            bold: true,
            margin: [0, 15, 0, 0]
          },
          { text: "" }
        ]
      },

      /* -------- PAGE FOOTER -------- */
      footer: function (currentPage, pageCount) {
        return {
          columns: [
            {
              text: `Generated by: M. A. Khan | 9001015311`,
              fontSize: 10,
              margin: [40, 0, 0, 0],
              color: "#333"
            },
            {
              text: `Page ${currentPage} of ${pageCount}`,
              alignment: "right",
              fontSize: 10,
              margin: [0, 0, 40, 0]
            }
          ]
        };
      },

      /* -------- CONTENT (TABLE) -------- */
      content: [
        {
          alignment: "center",
          table: {
            headerRows: 1,
            widths,
            body: [tableHeaders, ...tableRows]
          },
          layout: {
            fillColor: r => (r % 2 === 0 ? "#f2f2f2" : null),
            hLineWidth: () => 0.7,
            vLineWidth: () => 0.7,
            hLineColor: () => "#b5b5b5",
            vLineColor: () => "#b5b5b5"
          }
        }
      ],

      /* -------- STYLES -------- */
      styles: {
        tableHeader: {
          fillColor: "#1e293b",
          color: "white",
          bold: true,
          fontSize: 10
        },
        tableCell: {
          fontSize: 9,
          margin: 3
        }
      }
    };

    /* ------------------ GENERATE PDF -------------------- */
    const pdfDoc = printer.createPdfKitDocument(docDefinition);

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=filtered-data.pdf"
    );

    pdfDoc.pipe(res);
    pdfDoc.end();
  } catch (err) {
    console.error("PDF error:", err);
    res.status(500).json({ error: "PDF generation failed" });
  }
});

/* ==========================================================
   ROOT ROUTE
========================================================== */
app.get("/", (req, res) => {
  res.send("🚀 Backend is running successfully!");
});

/* ==========================================================
   START SERVER
========================================================== */
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🔥 Server running on port ${PORT}`));
